W7/D5/RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create] do
    resources :subs, only: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:create, :destroy]
end

W7/D5/RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User
    
end

W7/D5/RedditClone/app/models/user.rb
class User < ApplicationRecord
  before_validation :ensure_session_token

  attr_reader :password

  validates :username, :password_digest, presence: true
  validates :username, uniqueness: true
  validates :password, length: {minimum: 6}, allow_nil: true

  has_many :subs,
    foreign_key: :moderator_id,
    class_name: :Sub

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_valid_password?(password)
      return user
    else
      nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

end

W7/D5/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #HCRLLL

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_logged_in
    redirect_to subs_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def log_in(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end
  
end

W7/D5/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # new, create login, destroy logout
  before_action :require_logged_in, only: :destroy

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user.nil?
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    else
      log_in(@user)
      redirect_to subs_url
    end
  end

  def destroy
    log_out
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

W7/D5/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_logged_in, except: [:index, :show]
  before_action :is_moderator, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = params[:user_id]
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ["Must fill all text boxes"]
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ["Must fill all text boxes"]
      render :edit
    end
  end

  # def destroy
  #   sub = Sub.find(params[:id])
  #   sub.delete

  # end

  private
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def is_moderator
    sub = Sub.find(params[:id])
    if current_user.id != sub.moderator_id
      redirect_to sub_url(sub)
    end
  end

end

W7/D5/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # new, create Sign up 

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :password))
    if @user.save
      log_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid Username or Password"]
      render :new
    end
  end

end

W7/D5/RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7/D5/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

W7/D5/RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

W7/D5/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <ul>
        <li><%= current_user.username %></li>
        <li><a href="<%= new_sub_url %>">Create a Sub!</a></li>
        <li><a href="<%= subs_url %>">All subs!</a></li>
        <li><form action="<%= session_url %>" method="POST">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
          <input type="hidden" name="_method" value="DELETE">
          <input type="submit" value="Logout">
        </form></li>
      </ul>
    <% else %>
      <a href="<%= new_session_url %>">Sign in!</a>
    <% end %>
    <%= yield %>
  </body>
</html>

W7/D5/RedditClone/app/views/users/new.html.erb
<h1>New User!</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
  <label>
    Username: 
    <input type="text" name="user[username]" value="">
  </label>
  <br>
  <label>
    Password: 
    <input type="password" name="user[password]" value="">
  </label>
  <br>
  <input type="submit" value="Create User">
</form>

<% if flash[:errors] %>
  <p><%= flash[:errors] %></p>
<% end %>